/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...error].page': typeof import('./src/app/[...error].page.vue')['default']
    'AbsentIndex.page': typeof import('./src/app/absent/index.page.vue')['default']
    'AuthLogin.page': typeof import('./src/app/auth/login.page.vue')['default']
    'AuthLogout.page': typeof import('./src/app/auth/logout.page.vue')['default']
    'DashboardIndex.page': typeof import('./src/app/dashboard/index.page.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Index.page': typeof import('./src/app/index.page.vue')['default']
    ModalModalConfirmation: typeof import('./src/components/modal/modalConfirmation.vue')['default']
    ModalModalFiorm: typeof import('./src/components/modal/modalform.vue')['default']
    ModalModalform: typeof import('./src/components/modal/modalform.vue')['default']
    ModalModalForm: typeof import('./src/components/modal/ModalForm.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTable: typeof import('naive-ui')['NTable']
    'RoleaccesslistIndex.page': typeof import('./src/app/roleaccesslist/index.page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SSvg: typeof import('./src/components/s-svg/index.vue')['default']
    UserlistComponentsUserForm: typeof import('./src/app/userlist/components/userForm.vue')['default']
    UserlistComponentsUsertable: typeof import('./src/app/userlist/components/usertable.vue')['default']
    'UserlistIndex.page': typeof import('./src/app/userlist/index.page.vue')['default']
  }
}
